# coding=utf-8

from blocAndTools import buildingbloc as bloc
from blocAndTools.agent import Agent
from blocAndTools.buildingbloc import ExperimentSpec
from blocAndTools.visualisationtools import ConsolPrintLearningStats
from blocAndTools.container.samplecontainer import TrajectoryContainer, TrajectoryCollector, UniformBatchCollector, UniformeBatchContainer
from blocAndTools.rl_vocabulary import rl_name
from blocAndTools.temporal_difference_computation import computhe_the_Advantage, compute_TD_target, get_t_and_tPrime_array_view_for_element_wise_op
